//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllResourcesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllResourcesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.Shared.Resources.AllResourcesRes", typeof(AllResourcesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actualidad.
        /// </summary>
        public static string actualidad {
            get {
                return ResourceManager.GetString("actualidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo de aplicaciones en la nube y gestión de infraestructura.
        /// </summary>
        public static string Az204Descripcion {
            get {
                return ResourceManager.GetString("Az204Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparación para examen de Azure 204.
        /// </summary>
        public static string Az204Subtitulo {
            get {
                return ResourceManager.GetString("Az204Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formacion en Azure 204.
        /// </summary>
        public static string Az204Titulo {
            get {
                return ResourceManager.GetString("Az204Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenid@ esta es mi pagina web para mostrar mi CV, ¡Espero que te guste!.
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenid@!.
        /// </summary>
        public static string Bienvenidx {
            get {
                return ResourceManager.GetString("Bienvenidx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta página esta construida con Blazor, .Net ,publicada en Gihub Pages y utiizando la libreria Blazorise..
        /// </summary>
        public static string ConstruidoCon {
            get {
                return ResourceManager.GetString("ConstruidoCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prácticas obligatorias en el grado.Desarrollo Web orientado a cliente(BBVA), proyecto D4R(Data for Reputation)..
        /// </summary>
        public static string contratoPracticasGnossDescripcion {
            get {
                return ResourceManager.GetString("contratoPracticasGnossDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRATO DE PRÁCTICAS.
        /// </summary>
        public static string contratoPracticasGnossSubitulo {
            get {
                return ResourceManager.GetString("contratoPracticasGnossSubitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo de proyecto de fin de grado en la empresa. Durante este periodo he desarrollado un microservicio para añadir funcionalidad a una aplicación existente automatizando procesos relativos a la gestión de recursos humanos..
        /// </summary>
        public static string contratoPracticasHiberus1Descripcion {
            get {
                return ResourceManager.GetString("contratoPracticasHiberus1Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIBERUS · DESARROLLO TRABAJO FIN DE GRADO.
        /// </summary>
        public static string contratoPracticasHiberus1Subitulo {
            get {
                return ResourceManager.GetString("contratoPracticasHiberus1Subitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRATO DE PRÁCTICAS.
        /// </summary>
        public static string contratoPracticasHiberus1Titulo {
            get {
                return ResourceManager.GetString("contratoPracticasHiberus1Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRATO DE PRÁCTICAS.
        /// </summary>
        public static string contratoPracticasHiberus21Titulo {
            get {
                return ResourceManager.GetString("contratoPracticasHiberus21Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo de aplicación NetCore para gestión de recursos humanos y personal..
        /// </summary>
        public static string contratoPracticasHiberus2Descripcion {
            get {
                return ResourceManager.GetString("contratoPracticasHiberus2Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIBERUS · CONTRATO DE PRÁCTICAS.
        /// </summary>
        public static string contratoPracticasHiberus2Subitulo {
            get {
                return ResourceManager.GetString("contratoPracticasHiberus2Subitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo y maquetación de páginas con html y css.
        /// </summary>
        public static string CssHtmlMVPDescripcion {
            get {
                return ResourceManager.GetString("CssHtmlMVPDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación curso de desarrollo web.
        /// </summary>
        public static string CssHtmlMVPSubtitulo {
            get {
                return ResourceManager.GetString("CssHtmlMVPSubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html y CSS a fondo para desarrolladores.
        /// </summary>
        public static string CssHtmlMVPTitulo {
            get {
                return ResourceManager.GetString("CssHtmlMVPTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos y Certificaciones.
        /// </summary>
        public static string cursosCertificaciones {
            get {
                return ResourceManager.GetString("cursosCertificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACHILLER CIENTÍFICO.
        /// </summary>
        public static string descripcionBachiller {
            get {
                return ResourceManager.GetString("descripcionBachiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocimientos generales en distintas las áreas del Cloud Computing.
        /// </summary>
        public static string descripcionCloudComputing {
            get {
                return ResourceManager.GetString("descripcionCloudComputing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTUDIOS ELEMENTALES DE VIOLÍN.
        /// </summary>
        public static string descripcionConservatorio {
            get {
                return ResourceManager.GetString("descripcionConservatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos orientado a aprender nociones básicas del uso de contenedores y su utilización en proyectos de software..
        /// </summary>
        public static string descripcionContenedoresDocker {
            get {
                return ResourceManager.GetString("descripcionContenedoresDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo full stack utilizando blazor..
        /// </summary>
        public static string descripcionCursoBlazor {
            get {
                return ResourceManager.GetString("descripcionCursoBlazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En este curso se estudia el nuevo Framework de desarrollo de aplicaciones multiplataforma de código único y nociones básicas de NET6.
        /// </summary>
        public static string descripcionCursoMaui {
            get {
                return ResourceManager.GetString("descripcionCursoMaui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDUCACIÓN SECUNDARIA OBLIGATORIA.
        /// </summary>
        public static string descripcionEso {
            get {
                return ResourceManager.GetString("descripcionEso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos orientado a aprender nociones básicas del desarrollo web utilizando HTML5 , CSS y Javascript.
        /// </summary>
        public static string descripcionIntroduccionDesarrolloWeb {
            get {
                return ResourceManager.GetString("descripcionIntroduccionDesarrolloWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me especializo en la pila tecnológica de ASP.NET Core, con un enfocando el desarrollo de aplicaciones con sus procesos de CI/CD..
        /// </summary>
        public static string descripcionPersonal1 {
            get {
                return ResourceManager.GetString("descripcionPersonal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas: Español e Inglés.
        /// </summary>
        public static string descripcionPersonal3 {
            get {
                return ResourceManager.GetString("descripcionPersonal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se estudian aspectos básicos de la programación .NET desde el Front hasta Back. Usando principalmente mvc y sql server..
        /// </summary>
        public static string descripcionProgramacionNET {
            get {
                return ResourceManager.GetString("descripcionProgramacionNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre mi....
        /// </summary>
        public static string descripcionSobreMi1 {
            get {
                return ResourceManager.GetString("descripcionSobreMi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola, soy Héctor! Tengo 25 años he estudiado Ingeniería Informática. Y desde pequeño he tenido claro que quería dedicarme a la informática como forma de mejorar la vida de las personas y contribuir al progreso. También tengo otras aficiones como la música,los juegos de mesa, viajar, practicar deporte o simplemente leer un buen libro o una serie😃.
        /// </summary>
        public static string descripcionSobreMi2 {
            get {
                return ResourceManager.GetString("descripcionSobreMi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me considero una persona constante y trabajadora y creo que mi principal aptitud es el trabajo en equipo.
        /// </summary>
        public static string descripcionSobreMi3 {
            get {
                return ResourceManager.GetString("descripcionSobreMi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRADO EN INGENIERÍA INFORMÁTICA E INGENIERÍA DE SOFTWARE.
        /// </summary>
        public static string descripcionUniversidad {
            get {
                return ResourceManager.GetString("descripcionUniversidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación en contenedores docker.
        /// </summary>
        public static string DockerCertificatedAsociated {
            get {
                return ResourceManager.GetString("DockerCertificatedAsociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de trabajo de contenedores en docker y orquestación .
        /// </summary>
        public static string DockerCertificatedAsociatedDescription {
            get {
                return ResourceManager.GetString("DockerCertificatedAsociatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación en contendores docker.
        /// </summary>
        public static string DockerCertificatedAsociatedSubtitulo {
            get {
                return ResourceManager.GetString("DockerCertificatedAsociatedSubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación de entity framework, modelado de datos a través del framework orm de .net.
        /// </summary>
        public static string EntityFrameworkDeVerdadDescription {
            get {
                return ResourceManager.GetString("EntityFrameworkDeVerdadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación de EF Core.
        /// </summary>
        public static string EntityFrameworkDeVerdadSubtitle {
            get {
                return ResourceManager.GetString("EntityFrameworkDeVerdadSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso Entity Framework Core .
        /// </summary>
        public static string EntityFrameworkDeVerdadTitle {
            get {
                return ResourceManager.GetString("EntityFrameworkDeVerdadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de Arquitectura.
        /// </summary>
        public static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Arquitectura de Desarrollo.
        /// </summary>
        public static string GAD {
            get {
                return ResourceManager.GetString("GAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el equipo de GAD (Grupo de Arquitectura de Desarrollo) se trata de un equipo transversal que tiene como función principal dar soporte a los desarrolladores en aspectos relacionados con el desarrollo y la integración de sus productos en el proceso de CI/CD dentro de la organización..
        /// </summary>
        public static string GAD_descripcion {
            get {
                return ResourceManager.GetString("GAD_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Además del soporte también se llevan a cabo trabajos de mejora en la infraestructura de la organización por ejemplo implementando pipelines en Jenkins , implementando procesos de QA automatizados mediante SonarQube así como investigar y proponer nuevas tecnologías que ayuden a los desarrolladores en las necesidades del servicio..
        /// </summary>
        public static string GAD_descripcion2 {
            get {
                return ResourceManager.GetString("GAD_descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAD_descripcion2.
        /// </summary>
        public static string GAD_descripcion3 {
            get {
                return ResourceManager.GetString("GAD_descripcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Arquitectura Técnico.
        /// </summary>
        public static string GAT {
            get {
                return ResourceManager.GetString("GAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el equipo de GAT (Grupo de Arquitectura Técnica), desarrollamos la arquitectura base para nuevos productos que se integrarán en el servicio, así como para aquellos que están en proceso de migración. Esta arquitectura modular, construida en .NET 8, se basa en el enfoque de Diseño Orientado a Dominio (DDD)..
        /// </summary>
        public static string GAT_descripcion {
            get {
                return ResourceManager.GetString("GAT_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complementariamente a esto también se da soporte y se facilita las migraciones de tecnologías legacy proponiendo nuevas alternativas..
        /// </summary>
        public static string GAT_descripcion2 {
            get {
                return ResourceManager.GetString("GAT_descripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola Mundo!.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de la credencial:.
        /// </summary>
        public static string idCredencial {
            get {
                return ResourceManager.GetString("idCredencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguajes de Programación.
        /// </summary>
        public static string lenguagesProgramacion {
            get {
                return ResourceManager.GetString("lenguagesProgramacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodologías y principios.
        /// </summary>
        public static string metodologias {
            get {
                return ResourceManager.GetString("metodologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mes.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meses.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos.
        /// </summary>
        public static string navbar_cursos {
            get {
                return ResourceManager.GetString("navbar_cursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educacion.
        /// </summary>
        public static string navbar_educacion {
            get {
                return ResourceManager.GetString("navbar_educacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiencia.
        /// </summary>
        public static string navbar_experiencia {
            get {
                return ResourceManager.GetString("navbar_experiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string navbar_inicio {
            get {
                return ResourceManager.GetString("navbar_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SobreMi.
        /// </summary>
        public static string navbar_intereses {
            get {
                return ResourceManager.GetString("navbar_intereses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologías.
        /// </summary>
        public static string navbar_tecnologias {
            get {
                return ResourceManager.GetString("navbar_tecnologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participando en .
        /// </summary>
        public static string Participating {
            get {
                return ResourceManager.GetString("Participating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi trabajo en gobierno de Navarra se puede dividir en dos áreas: GAD y Vivienda..
        /// </summary>
        public static string programadorWebJuniorHiberusDescripcion1 {
            get {
                return ResourceManager.GetString("programadorWebJuniorHiberusDescripcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En el área de vivienda, mis funciones son realizar trabajos de mantenimiento y mejora de los diferentes productos de esta área. Los productos elaborados que se mantienen principalmente con tecnologías .NET Framework (principalmente WebForms).
        /// </summary>
        public static string programadorWebJuniorHiberusDescripcion3 {
            get {
                return ResourceManager.GetString("programadorWebJuniorHiberusDescripcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMADOR WEB PARA GOBIERNO DE NAVARRA.
        /// </summary>
        public static string programadorWebJuniorHiberusSubTitulo {
            get {
                return ResourceManager.GetString("programadorWebJuniorHiberusSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMADOR WEB.
        /// </summary>
        public static string programadorWebJuniorHiberusTitulo {
            get {
                return ResourceManager.GetString("programadorWebJuniorHiberusTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este curso proporciona un conocimiento detallado del framework de Scrum, enfatizando su proceso de implementación..
        /// </summary>
        public static string ScrumMasterDescripcion {
            get {
                return ResourceManager.GetString("ScrumMasterDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Framework: Scrum Master &amp; Product Owner Certified.
        /// </summary>
        public static string ScrumMasterSubtitulo {
            get {
                return ResourceManager.GetString("ScrumMasterSubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum Master &amp; Agile.
        /// </summary>
        public static string ScrumMasteTitulo {
            get {
                return ResourceManager.GetString("ScrumMasteTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduado en la Universidad de la Rioja en Ingeniería informática y mención en ingeniería de Software..
        /// </summary>
        public static string subtituloPersonal {
            get {
                return ResourceManager.GetString("subtituloPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESARROLLADOR &amp; INGENIERO DE SOFTWARE.
        /// </summary>
        public static string subtituloProfesional {
            get {
                return ResourceManager.GetString("subtituloProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemas de Control de versiones (SVC).
        /// </summary>
        public static string svcs {
            get {
                return ResourceManager.GetString("svcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Fundamentals.
        /// </summary>
        public static string tituloaz900 {
            get {
                return ResourceManager.GetString("tituloaz900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de contenedores Docker.
        /// </summary>
        public static string tituloContenedoresDocker {
            get {
                return ResourceManager.GetString("tituloContenedoresDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de Blazor.
        /// </summary>
        public static string tituloCursoBlazor {
            get {
                return ResourceManager.GetString("tituloCursoBlazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de NET MAUI y NET6.
        /// </summary>
        public static string tituloCursoMaui {
            get {
                return ResourceManager.GetString("tituloCursoMaui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTRODUCCIÓN AL DESARROLLO WEB I Y II.
        /// </summary>
        public static string tituloIntroduccionDesarrolloWeb {
            get {
                return ResourceManager.GetString("tituloIntroduccionDesarrolloWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programación .NET.
        /// </summary>
        public static string tituloProgramacionNET {
            get {
                return ResourceManager.GetString("tituloProgramacionNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso de React.
        /// </summary>
        public static string tituloReact {
            get {
                return ResourceManager.GetString("tituloReact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación de certificados:.
        /// </summary>
        public static string verificacionCertificados {
            get {
                return ResourceManager.GetString("verificacionCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación de documentos electrónicos:.
        /// </summary>
        public static string verificacionDocumentos {
            get {
                return ResourceManager.GetString("verificacionDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to año.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to años.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
