name: PublishApp
env:
  PUBLISH_DIR: bin/Release/net8.0/publish/wwwroot
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Controls when the action will run
on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #- name: abcd
      #run: |
        #pwd
        #ls -S

    - name: Publish app
      run: dotnet publish -c Release

    - name: Mostrar contenido del directorio
      run: ls -la

      
    # - name: Rewrite base href
    #   uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
    #   with:
    #     html_path: bin/Release/net8.0/wwwroot/index.html
    #     base_href: /CV/


    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}




