name: PublishApp

env:
  # Actualizamos la ruta de publicación para net9.0
  PUBLISH_DIR: bin/Release/net9.0/publish/wwwroot
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Instalamos .NET 9.0 (preview)
    - name: Install .NET 9.0 SDK
      run: |
        wget https://dotnet.microsoft.com/en-us/download/dotnet/scripts/v1/dotnet-install.sh
        chmod +x dotnet-install.sh
        ./dotnet-install.sh --channel 9.0

    - name: Display .NET version
      run: dotnet --version  # Verifica que la versión correcta se haya instalado

    - name: Publish app
      run: dotnet publish -c Release -f net9.0  # Publicar usando .NET 9.0

    - name: Mostrar contenido del directorio
      run: ls -la

    # - name: Rewrite base href
    #   uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
    #   with:
    #     html_path: bin/Release/net9.0/wwwroot/index.html
    #     base_href: /CV/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
